dataset:
  name: CAMELS_ES
  description: "CAMELS-ES: 269 Spanish catchments from Caravan extension"
  url: "https://zenodo.org/records/12575748"
  redistributable: true

source:
  reader: camels_es
  path: "${SF_DATA_DOWNLOADS}/CAMELS-ES"

variables:
  discharge: streamflow
  time: date
  station_id: gauge_id
  latitude: gauge_lat
  longitude: gauge_lon
  upstream_area: area

units:
  discharge: "mm/d"
  area: "km2"

timezone:
  type: fixed_offset
  utc_offset: 1.0
  definition: "CET (UTC+1, Spain)"

coordinate_system: "WGS84"

options: {}
