dataset:
  name: CAMELS_FR
  description: "CAMELS-FR: 654 French catchments, daily + monthly discharge"
  url: "https://doi.org/10.5281/zenodo.12785475"
  redistributable: true

source:
  reader: camels_fr
  path: "${SF_DATA_DOWNLOADS}/CAMELS_FR"

variables:
  discharge: tsd_q_l
  time: tsd_date
  station_id: sta_code_h3
  latitude: sta_y_w84
  longitude: sta_x_w84
  upstream_area: sta_area_snap

units:
  discharge: "L/s"
  area: "km2"

timezone:
  type: hydrological_day
  utc_offset: 1.0
  definition: "Hydrological day (UTC+1, France)"

coordinate_system: "WGS84"

options:
  resolutions:
    - daily
    - monthly
